spring:
  application:
    name: appeal-backend-v2
  servlet:
    multipart:
      max-request-size: 100MB  # 上传文件总的最大值 默认10MB
      max-file-size: 50MB
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:5432/license
    username: root
    password: 123456
server:
  address: 0.0.0.0
  port: 8102
  servlet:
    # session 30 天过期
    session:
      timeout: "P30D"
      cookie:
        same-site: none
        secure: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: available # 全局逻辑删除的实体字段名
      logic-delete-value: 0 # 逻辑已删除值（默认为 0）
      logic-not-delete-value: 1 # 逻辑未删除值（默认为 1）
